#pragma once

// pContext: TCHAR[MAX_PATH] Selected mesh path
#define EDITOR_EVENT_MESH_SELECTED "EDITOR_EVENT_MESH_SELECTED"

#define EDITOR_OBJECT_TYPE_PROP "Prop" 
#define EDITOR_OBJECT_TYPE_DIRECTIONAL_LIGHT "DirectionalLight" 
#define EDITOR_OBJECT_TYPE_POINT_LIGHT "PointLight" 
#define EDITOR_OBJECT_TYPE_SPOT_LIGHT "SpotLight" 
#define EDITOR_OBJECT_TYPE_BOX_COLLIDER "BoxCollider" 
#define EDITOR_OBJECT_TYPE_SPHERE_COLLIDER "SphereCollider" 
#define EDITOR_OBJECT_TYPE_CAPSULE_COLLIDER "CapsuleCollider" 
#define EDITOR_OBJECT_TYPE_PREFAB_PLAYER "Player"
#define EDITOR_OBJECT_TYPE_PREFAB_BEETLEDRONE "BeetleDrone"
#define EDITOR_OBJECT_TYPE_PREFAB_ANCIENTKING "AncientKing"
#define EDITOR_OBJECT_TYPE_PREFAB_ASHI "Ashi"
#define EDITOR_OBJECT_TYPE_EDITABLE_LAVA "Lava"
#define EDITOR_OBJECT_TYPE_BEETLE_SPAWNER "BeetleSapwner"
#define EDITOR_OBJECT_TYPE_GAS_VENT "GasVent"
#define EDITOR_OBJECT_TYPE_FLAME_VENT "FlameVent"
#define EDITOR_OBJECT_TYPE_DIRTGROUND "DirtGround"